version = 0.1

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "xxxxxxxxxxxxxx-dev"
s3_bucket = "common-dev-sam-artifactstore"
s3_prefix = "xxxxxxxxxxxxxx-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = """\
    EnvironmentName=\"dev\" \
"""
tags = "project=\"xxxxxxxxxxxxxx\" env=\"dev\" IaC=\"cfn\""
confirm_changeset = false

[prd]
[prd.deploy]
[prd.deploy.parameters]

