AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description:  xxxxxxxxxxxx
  

Globals:
  Function:
    MemorySize: 128  # default
    Timeout: 13


Parameters:
  ResourcePrefix:
    Type: String
    Default: xxxxxxxxxxxx
  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - prd


Resources:
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}-${EnvironmentName}-main
      CodeUri: functions/main
      Handler: src.app.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
    Metadata:  # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/app.ts
